# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrTest < Formula
  desc ""
  homepage "https://github.com/leberjs/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/gr-test/releases/download/v0.1.0/gr-test-darwin-amd64"
      sha256 "4f59870fd21d712ebe66852feb1f9ed1d21eefac4f5dff086858d457f0271509"

      def install
        bin.install "gr-test-darwin-amd64" => "gr-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leberjs/gr-test/releases/download/v0.1.0/gr-test-darwin-arm64"
      sha256 "9c7dfeec62d9af5412abb9a1b27a050abf5b7acf66acebb0713ee2304e532af4"

      def install
        bin.install "gr-test-darwin-arm64" => "gr-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leberjs/gr-test/releases/download/v0.1.0/gr-test-linux-arm64"
      sha256 "09ba23d11bc9cb97358e0eb4e9531a433a86f61d56b0d268605e610290a55c4f"

      def install
        bin.install "gr-test-linux-arm64" => "gr-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/gr-test/releases/download/v0.1.0/gr-test-linux-amd64"
      sha256 "39db98def5f2bad2c5942c2905ee0f0bfca87436741f1a078c048eb362d1dc6d"

      def install
        bin.install "gr-test-linux-amd64" => "gr-test"
      end
    end
  end
end
