# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pebble < Formula
  desc ""
  homepage "https://github.com/leberjs/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-darwin-arm64"
      sha256 "efc53da18373879f083857997d1c3ddd0455a2a221ba2f861e0d1bfe883ce43d"

      def install
        bin.install "pbl-darwin-arm64" => "pbl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-darwin-amd64"
      sha256 "35aa9ab7e3186b82f291357897268231a71d368b6cd4526af3d1d44915d145e1"

      def install
        bin.install "pbl-darwin-amd64" => "pbl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-linux-arm64"
      sha256 "9e8b135019df8a83510b2a2382d8ae1fcd59eb544d77b24fedb7e078545df803"

      def install
        bin.install "pbl-linux-arm64" => "pbl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-linux-amd64"
      sha256 "adf001e17e45c36414b5e87f223061e68b351e5031cb86665f659d082e4a5fea"

      def install
        bin.install "pbl-linux-amd64" => "pbl"
      end
    end
  end
end
