# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pebble < Formula
  desc ""
  homepage "https://github.com/leberjs/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-darwin-arm64"
      sha256 "8a08858e2f2b97a94b41938a6a93f04b7819227e7295e089a184bc76c64db2ad"

      def install
        bin.install "pbl-darwin-arm64" => "pbl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-darwin-amd64"
      sha256 "bcc1ab1a8c4f61d394ef01818bee8b24fe3570f40f07430f3fb8c2f75335b059"

      def install
        bin.install "pbl-darwin-amd64" => "pbl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-linux-amd64"
      sha256 "b525194a178acaf3a5cff4f7e0c9b60a62733a7405bba82f562c969be1ad9939"

      def install
        bin.install "pbl-linux-amd64" => "pbl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leberjs/pebble/releases/download/v0.1.0/pbl-linux-arm64"
      sha256 "c5082008f93b0f365af9b171ca030c63ca7d373968e4450be161e77c465fb3ce"

      def install
        bin.install "pbl-linux-arm64" => "pbl"
      end
    end
  end
end
